### PR TITLE
Avoid using indirect calls

### PR DESCRIPTION
**Pull request by atoomic**

### CODE REVIEW

**Comment by pmqs** [comment]
Hey @atoomic 

What is the thinking behind this change (plus the same one being done for other dual-life modules)? 

I know all about why the indirect call should be avoided, but my inner C++ programmer has a preference for the `new Module` form. :-)

**Comment by atoomic** [comment]
Hi @pmqs the main reason on updating the dual life to stop using indirect calls is to start moving to the vision described by @xsawyerx today in this video https://www.youtube.com/watch?v=6wPMh-3qYJM

We hope that indirect notation will not be enabled by default in future versions of Perl.
I'm currently patching dual life modules in order to be able to promote such standards in the next iteration of Perl.
You can view a prototype from https://github.com/Perl/perl5/tree/core-p7

thanks for considering this patch

**Comment by pmqs** [comment]
Thanks @atoomic. Just seen the announcement on p5p about Perl7.  Will get this mergerd

**Comment by atoomic** [comment]
@pmqs I just rebased and resolved conflicts with recent changes
Thanks for considering this change

**Comment by atoomic** [comment]
thanks

**Pull request merged**
