### PR TITLE
Created LICENSE

### PR DESCRIPTION
**Pull request by ranwitter**
Added Perl5 License to support SCA Toolchains like Synopsis Blackduck. 

Without this License most automatic SCA Toolchains says no License detected.

### CODE REVIEW

**Comment by pmqs** [comment]
Thanks for the patch, but the GNU license is not appropriate for this code.

**Comment by pmqs** [comment]
The Perl artistic License 2.0 (https://opensource.org/license/artistic-2-0/) applies to this module.

What issue is this solving?

**Comment by pmqs** [comment]
Does the file not have to contain the complete license text? Perhaps add a link to the definitive source, like https://www.perlfoundation.org/artistic-license-20.html ? Does that still keep the automatic checkers happy?

**Comment by ranwitter** [comment]
Most automated SCA Tools scan for distributed verbatim copies of license document and hence a Link is not sufficient.

**Comment by pmqs** [comment]
> Most automated SCA Tools scan for distributed verbatim copies of license document and hence a Link is not sufficient.

Hmm, but this isn't verbatim copy of the licence file. You have changed the formatting and added peoples names.

Are you aware that this code is also shipped with the official Perl distribution, which (I think) has a licence file. Does that matter for your use case?

Also - there are modules that are included by `IO::Compress`, namely `Compress::Raw::Zlib` and `Compress::Raw::Bzip2`, Does your automation not flag them as well?

**Comment by ranwitter** [comment]
In our use case we have deployed all three modules above, downloaded from CPAN.org and dynamically linked under PERL5LIB.

**Comment by Grinnz** [comment]
As posted on the p5p mailing list:

Artistic 1 and 2 are separate licenses that cannot be interchanged, and unfortunately Perl is licensed with "Artistic 1.0 OR GPL 1+", which cannot reasonably be changed. As the license of this distribution appears to be "same as Perl itself", the generated LICENSE file should match this. The easiest way to generate such a file correctly is with the software-license program https://metacpan.org/pod/App::Software::License:

software-license --holder 'Paul Marquess' --year 1995 --license Perl_5 --type license > LICENSE

(you can edit the generated year to the year range as listed in the docs, but the application seems to require an integer)

**Comment by ranwitter** [comment]
Thank you for the kind investigation. Yes SCA tool can be redirected to look into README file.

**Comment by pmqs** [comment]
> Thank you for the kind investigation. Yes SCA tool can be redirected to look into README file.

Excellent! Good to hear that you have it sorted.

**Pull request closed without merging**
